name: keras
channels:
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit>=11.4
  - cuda-cupti>=11.4
  - cudnn>=8.2
  - keras==2.6.0
  - pip
  - pip:
      - mlflow
      - tensorflow
